# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow
media_folder: "/src/images"
public_folder: "/src/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    fields:
      - { name: Title }
